### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by henrysource** [xdite/bootstrappers#1]
OS: Ubuntu 12.04

Ruby: 1.9.3-p194 (installed by rbenv)

Command Line: Zsh + Oh my Zsh

After i install this gem latest version (0.0.3), I try to run  `bootstrappers project_name`  to create new project

and it says "zsh: command not found: bootstrappers"

I am sure it installed successfully.

Hope to fix this bug.

**Comment by xdite** [comment]
please install 0.0.4 , stupid typo XD
