### ISSUE TITLE
I can create a new project, but I can't use command 'rails server' to preview it

### ISSUE THREAD

**Issue by homeway** [xdite/bootstrappers#15]
Started GET "/" for 127.0.0.1 at 2013-08-05 21:08:55 +0800
Processing by HighVoltage::PagesController#show as HTML
  Parameters: {"id"=>"welcome"}
  Rendered pages/welcome.html.erb within layouts/application (5.2ms)
Compiled common.css  (1756ms)  (pid 50879)
Compiled application.css  (1820ms)  (pid 50879)
  Rendered common/_search_form.html.erb (0.6ms)
  Rendered common/_user_nav.html.erb (1.6ms)
  Rendered common/_menu.html.erb (4.1ms)
  Rendered common/_footer.html.erb (0.4ms)
  Rendered common/_bootstrap_modal.html.erb (0.2ms)
  Rendered common/_facebook_js.erb (0.3ms)
  Rendered common/_google_analytics.html.erb (0.3ms)
Completed 500 Internal Server Error in 1973ms

Sprockets::FileNotFound - couldn't find file 'jquery-ui'
  (in /Users/homeway/ruby/workspace/project_5/app/assets/javascripts/application.js:4):
  sprockets (2.2.2) lib/sprockets/context.rb:102:in `resolve'
  sprockets (2.2.2) lib/sprockets/context.rb:142:in`require_asset'
  sprockets (2.2.2) lib/sprockets/directive_processor.rb:215:in `process_require_directive'
  sprockets (2.2.2) lib/sprockets/directive_processor.rb:165:in`block in process_directives'
  sprockets (2.2.2) lib/sprockets/directive_processor.rb:163:in `process_directives'
  sprockets (2.2.2) lib/sprockets/directive_processor.rb:97:in`evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.2.2) lib/sprockets/context.rb:193:in`block in evaluate'
  sprockets (2.2.2) lib/sprockets/context.rb:190:in `evaluate'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/processed_asset.rb:16:in`initialize'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `block in build_asset'
  sprockets (2.2.2) lib/sprockets/base.rb:270:in`circular_call_protection'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/base.rb:14:in `build_asset'
  sprockets (2.2.2) lib/sprockets/index.rb:93:in`block in build_asset'
  sprockets (2.2.2) lib/sprockets/caching.rb:19:in `cache_asset'
  sprockets (2.2.2) lib/sprockets/index.rb:92:in`build_asset'
  sprockets (2.2.2) lib/sprockets/base.rb:169:in `find_asset'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/index.rb:14:in`find_asset'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/bundled_asset.rb:12:in `initialize'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/base.rb:22:in`build_asset'
  sprockets (2.2.2) lib/sprockets/index.rb:93:in `block in build_asset'
  sprockets (2.2.2) lib/sprockets/caching.rb:19:in`cache_asset'
  sprockets (2.2.2) lib/sprockets/index.rb:92:in `build_asset'
  sprockets (2.2.2) lib/sprockets/base.rb:169:in`find_asset'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
  turbo-sprockets-rails3 (0.3.6) lib/turbo-sprockets/sprockets_overrides/environment.rb:15:in`find_asset'
  sprockets (2.2.2) lib/sprockets/base.rb:177:in `[]'
  actionpack (3.2.11) lib/sprockets/helpers/rails_helper.rb:126:in`asset_for'
  actionpack (3.2.11) lib/sprockets/helpers/rails_helper.rb:27:in `block in javascript_include_tag'
  actionpack (3.2.11) lib/sprockets/helpers/rails_helper.rb:26:in`javascript_include_tag'
  app/views/layouts/application.html.erb:47:in `_app_views_layouts_application_html_erb___3576656469312628017_70260074560960'
  actionpack (3.2.11) lib/action_view/template.rb:145:in`block in render'
  activesupport (3.2.11) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.11) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:45:in`render_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.11) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /Users/homeway/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:39:in`render'
  high_voltage (1.2.4) app/controllers/high_voltage/pages_controller.rb:25:in `show'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.11) lib/active_support/callbacks.rb:425:in`_run__1243908459892787858__process_action__2956047396743621027__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in`call'
  omniauth (1.1.4) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.1.4) lib/omniauth/strategy.rb:164:in`call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__4226732904204068204__call__4222641384807205143__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/reloader.rb:65:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  airbrake (3.1.12) lib/airbrake/rails/middleware.rb:13:in`call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:79:in`better_errors_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in `call'
  airbrake (3.1.12) lib/airbrake/user_informer.rb:16:in`_call'
  airbrake (3.1.12) lib/airbrake/user_informer.rb:12:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in`call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in`call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in`service'
  /Users/homeway/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /Users/homeway/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
  /Users/homeway/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

Started POST "/__better_errors/70260049870940/variables" for 127.0.0.1 at 2013-08-05 21:08:57 +0800

**Comment by southwolf** [comment]
The error message is "Sprockets::FileNotFound - couldn't find file 'jquery-ui'"
you should check that

**Comment by homeway** [comment]
Thank you! It worked well after I do this:
1. add 'jquery-ui-rails' to the Gemfile
2. change the item in application.js:
   //= require jquery.ui.all
