### ISSUE TITLE
bootstrap-setting.css.scss 與 bootstrap-override.css.scss 內容被重複載入

### ISSUE THREAD

**Issue by tka** [xdite/bootstrappers#3]
https://github.com/xdite/bootstrappers/blob/master/lib/bootstrappers/app_builder.rb#L105 這行的功能是塞了預設的 scss 檔案到 application.css.scss 中, 但是 application.css.scss 原本就有 `require_tree .` 的功能, 造成 `bootstrap-setting.css.scss` 跟 `bootstrap-override.css.scss` 的內容被重複載入

**Comment by xdite** [comment]
should fixed in 0.0.9, thanks
