### ISSUE TITLE
Created a new project using this bootstrappers, but how to go next?

### ISSUE THREAD

**Issue by sgarwang** [xdite/bootstrappers#6]
Can you recommend ways for accounts, such as how to setup current_user?
Thanks!

NameError in High_voltage/pages#show

Showing /Users/sgarwang/Desktop/github/xdite_rock/app/views/common/_user_nav.html.erb where line #7 raised:

undefined local variable or method `current_user' for #<#Class:0x10deb9d40:0x10deaf598>

**Comment by xdite** [comment]
`current_user` is provided by devise.

You may need to `bundle install` & `touch tmp/restart.txt` then reopen browser
